//*****************************************************************************
// [システム]  T&G テレフォンレポート管理
// 
// [機能概要]  組織マスタ。
//
// [作成履歴]　2014/06/25  屠錦栄　初版 
//
// [レビュー]　2014/07/17  屠錦栄　 
//*****************************************************************************
using WebEvaluation.Models;
using System.Data.Entity.Migrations;

namespace WebEvaluation.DAL
{
    /// <summary>
    /// 名称テーブル
    /// </summary>
    public class S_UnitData
    {
        public static S_Unit[] GetData()
        {
            return new S_Unit[] { };
        }

        public static void Seed(WebEvaluation.DAL.EvaluationContext context)
        {
            context.Units.AddOrUpdate(GetData());
            context.SaveChanges();
        }
    }
}
//new S_Unit {  UnitCD = "A000000000",  UnitName = "Ｔ＆Ｇ",  ShopCD = "" , IsShop =false,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A000000020",  UnitName = "内部監査部",  ShopCD = "" , IsShop =false,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A000000030",  UnitName = "広報部",  ShopCD = "" , IsShop =false,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A000000035",  UnitName = "総務部",  ShopCD = "" , IsShop =false,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A000000040",  UnitName = "カスタマーセンター",  ShopCD = "" , IsShop =false,IsCusCenter=true} ,
//new S_Unit {  UnitCD = "A000000050",  UnitName = "財務経理部",  ShopCD = "" , IsShop =false,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A000000051",  UnitName = "経営企画部",  ShopCD = "" , IsShop =false,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A000000052",  UnitName = "T&G ROYAL SPA",  ShopCD = "" , IsShop =false,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A000000053",  UnitName = "国際事業部",  ShopCD = "" , IsShop =false,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A000000060",  UnitName = "人事部",  ShopCD = "" , IsShop =false,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A000000070",  UnitName = "ｸﾘｴｲﾃｨﾌﾞｾﾝﾀｰ",  ShopCD = "" , IsShop =false,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A000000071",  UnitName = "ｸﾘｴｲﾃｨﾌﾞ運営",  ShopCD = "" , IsShop =false,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A000000072",  UnitName = "ｸﾘｴｲﾃｨﾌﾞ商品",  ShopCD = "" , IsShop =false,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A000000073",  UnitName = "ｸﾘｴｲﾃｨﾌﾞ開発",  ShopCD = "" , IsShop =false,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A000000074",  UnitName = "ｸﾘｴｲﾃｨﾌﾞＴＧＲＣ",  ShopCD = "" , IsShop =false,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A000000075",  UnitName = "ｸﾘｴｲﾃｨﾌﾞ教育",  ShopCD = "" , IsShop =false,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A000100000",  UnitName = "運営統括本部",  ShopCD = "" , IsShop =false,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A000100002",  UnitName = "料飲統括部",  ShopCD = "" , IsShop =false,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A000100003",  UnitName = "ＯＰ統括部",  ShopCD = "" , IsShop =false,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A000100005",  UnitName = "レストラン統括部",  ShopCD = "" , IsShop =false,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A000100006",  UnitName = "東日本事業部",  ShopCD = "" , IsShop =false,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A000100007",  UnitName = "関東事業部",  ShopCD = "" , IsShop =false,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A000100008",  UnitName = "東海事業部",  ShopCD = "" , IsShop =false,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A000100009",  UnitName = "関西事業部",  ShopCD = "" , IsShop =false,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A000100011",  UnitName = "西日本事業部",  ShopCD = "" , IsShop =false,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A000100014",  UnitName = "不動産開発部",  ShopCD = "" , IsShop =false,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A000100015",  UnitName = "事業推進部",  ShopCD = "" , IsShop =false,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A000100017",  UnitName = "店舗管理部",  ShopCD = "" , IsShop =false,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A000100018",  UnitName = "営業推進部",  ShopCD = "" , IsShop =false,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A000100019",  UnitName = "B&C Sales Task Force",  ShopCD = "" , IsShop =false,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A000100020",  UnitName = "ﾏｰｹﾃｨﾝｸﾞ戦略部",  ShopCD = "" , IsShop =false,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A000100100",  UnitName = "ＭＤ部",  ShopCD = "" , IsShop =false,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A000110001",  UnitName = "マーケティング本部",  ShopCD = "" , IsShop =false,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A000110002",  UnitName = "D&A Task Force",  ShopCD = "" , IsShop =false,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A00011002A",  UnitName = "ＡＫ",  ShopCD = "AK" , IsShop =true,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A00011004A",  UnitName = "ＡＺ",  ShopCD = "AZ" , IsShop =true,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A00011005A",  UnitName = "ＡＴ",  ShopCD = "AT" , IsShop =true,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A00011006A",  UnitName = "ＡＳ",  ShopCD = "AS" , IsShop =true,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A00011007C",  UnitName = "ＡＫＵ",  ShopCD = "AKU" , IsShop =true,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A00011008A",  UnitName = "ＡＫＦ",  ShopCD = "AKF" , IsShop =true,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A00011009A",  UnitName = "ＡＫＮ",  ShopCD = "AKN" , IsShop =true,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A00011010A",  UnitName = "ＡＫＳ",  ShopCD = "AKS" , IsShop =true,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A00011011A",  UnitName = "ＡＦＦ",  ShopCD = "AFF" , IsShop =true,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A00011012A",  UnitName = "ＡＦＫ",  ShopCD = "AFK" , IsShop =true,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A00011014C",  UnitName = "ＡＴＴ",  ShopCD = "ATT" , IsShop =true,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A00011015A",  UnitName = "ＡＴＯ",  ShopCD = "ATO" , IsShop =true,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A00011016C",  UnitName = "ＡＣＭ",  ShopCD = "ACM" , IsShop =true,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A00011017C",  UnitName = "ＡＣＨ",  ShopCD = "ACH" , IsShop =true,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A00011018C",  UnitName = "ＡＣＮ",  ShopCD = "ACN" , IsShop =true,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A00011019A",  UnitName = "ＡＣＫ",  ShopCD = "ACK" , IsShop =true,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A00011020A",  UnitName = "ＡＶＨ",  ShopCD = "AVH" , IsShop =true,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A00011021A",  UnitName = "ＡＶＮ",  ShopCD = "AVN" , IsShop =true,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A00011022C",  UnitName = "ＡＶＴ",  ShopCD = "AVT" , IsShop =true,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A00011023C",  UnitName = "ＡＣＩ",  ShopCD = "ACI" , IsShop =true,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A00011024A",  UnitName = "ＡＶＯ",  ShopCD = "AVO" , IsShop =true,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A00011025A",  UnitName = "ＹＧ",  ShopCD = "YG" , IsShop =true,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A00011026C",  UnitName = "ＢＧ",  ShopCD = "BG" , IsShop =true,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A00011027C",  UnitName = "ＨＣＧ",  ShopCD = "HCG" , IsShop =true,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A00011028C",  UnitName = "ＡＴＨ",  ShopCD = "ATH" , IsShop =true,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A00011029C",  UnitName = "ＡＶＯＫ",  ShopCD = "AVOK" , IsShop =true,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A00011030A",  UnitName = "ＢＧＫ",  ShopCD = "BGK" , IsShop =true,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A00011031A",  UnitName = "ＹＧＫ",  ShopCD = "YGK" , IsShop =true,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A00011032A",  UnitName = "ＡＴＴＯ",  ShopCD = "ATTO" , IsShop =true,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A00011033C",  UnitName = "ＢＧＫＡ",  ShopCD = "BGKA" , IsShop =true,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A00011034A",  UnitName = "ＫＧ",  ShopCD = "KG" , IsShop =true,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A00011035A",  UnitName = "ＡＦＯ",  ShopCD = "AFO" , IsShop =true,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A00011036C",  UnitName = "ＧＨＯ",  ShopCD = "GHO" , IsShop =true,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A00011037C",  UnitName = "ＡＦＧ",  ShopCD = "AFG" , IsShop =true,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A00011038C",  UnitName = "ＢＰＯ",  ShopCD = "BPO" , IsShop =true,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A00011039A",  UnitName = "ＡＣＦ",  ShopCD = "ACF" , IsShop =true,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A00011040A",  UnitName = "ＳＧ",  ShopCD = "SG" , IsShop =true,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A00011041C",  UnitName = "ＡＦＫＯ",  ShopCD = "AFKO" , IsShop =true,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A00011042C",  UnitName = "ＢＰＣ",  ShopCD = "BPC" , IsShop =true,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A00011043C",  UnitName = "ＢＧＮ",  ShopCD = "BGN" , IsShop =true,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A00011044C",  UnitName = "ＧＨＮ",  ShopCD = "GHN" , IsShop =true,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A00011045A",  UnitName = "ＡＧＯ",  ShopCD = "AGO" , IsShop =true,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A00011046C",  UnitName = "ＢＧＭ",  ShopCD = "BGM" , IsShop =true,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A00011047A",  UnitName = "ＡＧＮＵ",  ShopCD = "AGNU" , IsShop =true,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A00011048A",  UnitName = "ＡＱＹ",  ShopCD = "AQY" , IsShop =true,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A00011049C",  UnitName = "ＢＧＷ",  ShopCD = "BGW" , IsShop =true,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A00011051A",  UnitName = "ＡＱＳＩ",  ShopCD = "AQSI" , IsShop =true,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A00011052C",  UnitName = "ＧＣＹＯ",  ShopCD = "GCYO" , IsShop =true,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A00011053C",  UnitName = "ＧＨＯＯ",  ShopCD = "GHOO" , IsShop =true,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A00011054C",  UnitName = "ＧＨＭ",  ShopCD = "GHM" , IsShop =true,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A00011055C",  UnitName = "ＡＶＴＡ",  ShopCD = "AVTA" , IsShop =true,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A00011056A",  UnitName = "ＢＧＳ",  ShopCD = "BGS" , IsShop =true,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A00011057A",  UnitName = "ＣＨＹ",  ShopCD = "CHY" , IsShop =true,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A00011058A",  UnitName = "ＡＧＯＫ",  ShopCD = "AGOK" , IsShop =true,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A00011059A",  UnitName = "ＡＴＳＩ",  ShopCD = "ATSI" , IsShop =true,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A00011060A",  UnitName = "ＨＣＳ",  ShopCD = "HCS" , IsShop =true,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A00011061A",  UnitName = "ＣＧ",  ShopCD = "CG" , IsShop =true,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A00011062A",  UnitName = "ＨＣＴ",  ShopCD = "HCT" , IsShop =true,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A00011063A",  UnitName = "ＡＯ",  ShopCD = "AO" , IsShop =true,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A00011064A",  UnitName = "ＯＴ",  ShopCD = "OT" , IsShop =true,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A00011065A",  UnitName = "ＳＣ",  ShopCD = "SC" , IsShop =true,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A00011066A",  UnitName = "ＭＣ",  ShopCD = "MC" , IsShop =true,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A00012001R",  UnitName = "ＢＵ",  ShopCD = "BU" , IsShop =true,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A00012003R",  UnitName = "ＴＥ",  ShopCD = "TE" , IsShop =true,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A00012005R",  UnitName = "ＭＡ",  ShopCD = "MA" , IsShop =true,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A00012009R",  UnitName = "ＦＥ",  ShopCD = "FE" , IsShop =true,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A00012024R",  UnitName = "ＦＢＴ",  ShopCD = "FBT" , IsShop =true,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A00012025R",  UnitName = "ＣＹＣ",  ShopCD = "CYC" , IsShop =true,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A00012026R",  UnitName = "ＴＤ",  ShopCD = "TD" , IsShop =true,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A00013002F",  UnitName = "ＦＤＷ（ＡＫ）",  ShopCD = "" , IsShop =false,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A00013003F",  UnitName = "ＦＤＷ（ＡＺ）",  ShopCD = "" , IsShop =false,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A00013004F",  UnitName = "ＦＤＷ（ＡS）",  ShopCD = "" , IsShop =false,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A00013005F",  UnitName = "ＦＤＷ（ＭＡ）",  ShopCD = "" , IsShop =false,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A00013006F",  UnitName = "ＦＤＷ（ＳＣ）",  ShopCD = "" , IsShop =false,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A00013010F",  UnitName = "ＦＤＷ（ＯＴ）",  ShopCD = "" , IsShop =false,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A00013011F",  UnitName = "ＦＣ神戸（ＢＧＫ）",  ShopCD = "" , IsShop =false,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A00013012F",  UnitName = "ＦＣ神戸（ＹＧＫ）",  ShopCD = "" , IsShop =false,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A00013013F",  UnitName = "ＦＣ静岡（ＡＴＳＩ）",  ShopCD = "" , IsShop =false,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A00013014F",  UnitName = "ＦＣ静岡（ＢＧＳ）",  ShopCD = "" , IsShop =false,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A00015001R",  UnitName = "ＢＰ",  ShopCD = "BP" , IsShop =true,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A00015002R",  UnitName = "ＬＰ",  ShopCD = "LP" , IsShop =true,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A00015003R",  UnitName = "ＪＷＬ",  ShopCD = "JWL" , IsShop =true,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A00016001H",  UnitName = "ＢＶ",  ShopCD = "BV" , IsShop =true,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A00016004H",  UnitName = "ＣＰＫ",  ShopCD = "CPK" , IsShop =true,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A00016005H",  UnitName = "ＢＰＫ",  ShopCD = "BPK" , IsShop =true,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A00016006H",  UnitName = "ＭＹＫ",  ShopCD = "MYK" , IsShop =true,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A00016008H",  UnitName = "ＧＴＭ",  ShopCD = "GTM" , IsShop =true,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A00016010H",  UnitName = "ＡＣＰＫ",  ShopCD = "ACPK" , IsShop =true,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A110000000",  UnitName = "ﾌﾞﾗｲｽﾞﾜｰﾄﾞ",  ShopCD = "" , IsShop =false,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A120000000",  UnitName = "ＳＳＹ",  ShopCD = "SSY" , IsShop =true,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A130000000",  UnitName = "ＣＣＧ",  ShopCD = "CCG" , IsShop =true,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A140000000",  UnitName = "ＴＡＧ",  ShopCD = "TAG" , IsShop =true,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A200000000",  UnitName = "ﾗｲﾌｴﾝｼﾞｪﾙ",  ShopCD = "" , IsShop =false,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A300000000",  UnitName = "ｱﾆﾊﾞｰｻﾘｰﾄﾗﾍﾞﾙ",  ShopCD = "" , IsShop =false,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A600000000",  UnitName = "ﾐﾗｷｭﾙｰｽﾞ",  ShopCD = "" , IsShop =false,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A600000001",  UnitName = "ﾗ･ﾒｰﾙ･ﾌﾟﾗｰﾙ",  ShopCD = "" , IsShop =false,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A700000000",  UnitName = "ｸﾞｯﾄﾞﾗｯｸ・ｺｰﾎﾟﾚｰｼｮﾝ",  ShopCD = "" , IsShop =false,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A800000000",  UnitName = "ＶＧＥ",  ShopCD = "VGE" , IsShop =true,IsCusCenter=false} ,
//new S_Unit {  UnitCD = "A800000001",  UnitName = "ウィーブ",  ShopCD = "" , IsShop =false,IsCusCenter=false} ,